services:
  fcp-fd-file-receiver:
    build:
      context: .
      target: production
    image: fcp-fd-file-receiver
    container_name: fcp-fd-file-receiver
    environment:
      APPINSIGHTS_CLOUDROLE: fcp-fd-file-receiver-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
