# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  fcp-fd-file-receiver:
    build:
      target: development
    image: fcp-fd-file-receiver-development
    container_name: fcp-fd-file-receiver-development
    ports:
      - "3020:3020"
      - "9020:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
