{{- if .Values.usePodIdentity }}
{{- include "ffc-helm-library.azure-identity" (list . "fcp-fd-file-receiver.azure-identity") -}}
{{- end -}}
{{- define "fcp-fd-file-receiver.azure-identity" -}}
{{- end -}}