environment: production
environmentCode:
name: fcp-fd-file-receiver
namespace: fcp-fd
workstream: fcp-fd
image: fcp-fd-file-receiver

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: fcp-fd-file-receiver-config-map

containerSecret:
  name: fcp-fd-file-receiver-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3020

livenessProbe:
  path: /healthz
  port: 3020
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3020
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

usePodIdentity: true

azureIdentity:
  resourceID: not-a-real-resource-id
  clientID: not-a-real-client-id